### ISSUE TITLE
Typo in the OperatorPrecedenceParser documentation

### ISSUE THREAD

**Issue by ZelteHonor** [stephan-tolksdorf/fparsec#10]
I don't know if this is the right place to talk about it, but I think there is a word missing here. 

http://www.quanttec.com/fparsec/reference/operatorprecedenceparser.html#members.Precedence

Shouldn't it be: The value is always greater than zero. instead of: The value is always greater zero.

**Comment by stephan-tolksdorf** [comment]
Thanks you for pointing out this typo! I've just fixed it.
