### ISSUE TITLE
`opt` fails to parse into tuple

### ISSUE THREAD

**Issue by tymokvo** [stephan-tolksdorf/fparsec#106]
Hello,

I am trying to create a parser for strings with an optional field that is failing in an unexpected way.

Parsing an optional int works as expected:

```fsharp
#r "nuget: FParsec"

open FParsec
open FParsec.Primitives

let test p str =
    match run p str with
    | Success(res, _, _) -> printfn "Success: '%s' -> %A" str res
    | Failure(msg, _, _) -> printfn "Failure: %s" msg

let parse: Parser<_, unit> = pint32 |> opt

let main _ = [ "1"; "_" ] |> List.map (test parse)

main ()
```
Output:
```console
Success: '1' -> Some 1
Success: '_' -> None
```

However, parsing an optional int as part of a tuple fails:

```fsharp
#r "nuget: FParsec"

open FParsec
open FParsec.Primitives

let test p str =
    match run p str with
    | Success(res, _, _) -> printfn "Success: '%s' -> %A" str res
    | Failure(msg, _, _) -> printfn "Failure: %s" msg

let parse: Parser<_, unit> = pint32 |> opt .>>. pchar 'a'

let main _ = [ "1a"; "_a" ] |> List.map (test parse)

main ()
```
Output:
```console
Success: '1a' -> (Some 1, 'a')
Failure: Error in Ln: 1 Col: 1
_a
^
Expecting: integer number (32-bit, signed) or 'a'
```
I would have expected the output to be:
```console
Success: '1a' -> (Some 1, 'a')
Success: '_a' -> (None, 'a')
```

Am I using the combination of `opt` and `.>>.` incorrectly? Based on the [`opt`](http://www.quanttec.com/fparsec/reference/primitives.html#members.opt) documentation, I think my expectation is reasonable, but I must be missing something.

**Comment by Martin521** [comment]
Your second parser is correct, I think, as the following test shows.
`[ "1a"; "a" ] |> List.iter (test parse)`
You have nothing in your parser that can parse the underline character.

**Comment by tymokvo** [comment]
I guess that is my question then: why is the `_` ignored in the first case but not in the second? I take it that it is because the parser has reached the end of the input stream? E.g. reversing the second parser to become `Parser<(char * int option), unit>` and the input string to `a_` returns `('a', None)` as I would expect.

Is there another pattern to express "try to parse `<type>`, if it fails then consume the input, return `None` and continue`.

**Comment by Martin521** [comment]
> why is the _ ignored in the first case but not in the second?

In the first case the `_` is not ignored but just not parsed yet.

> Is there another pattern to express "try to parse <type>, if it fails then consume the input, return None and continue`.

What do you mean by "consume the input"? Until the end of the input stream? Or one character? If the alternative to the `int` is not nothing (this is what the `opt` parser is for), but some other string, you have to specify it. Check out the [tutorial](https://www.quanttec.com/fparsec/users-guide/parsing-alternatives.html) to see how this works.

**Comment by tymokvo** [comment]
> What do you mean by "consume the input"? Until the end of the input stream?

I think a more specific version of my question would be "consume the input until the next parser succeeds or the end of the input stream".

The behavior that I find surprising (and not that it's wrong, just that I'm trying to understand how to use the library most productively) is that `opt` behaves as if it consumes the rest of the input stream _only_ when it is the last parser in a sequence.

**Comment by Martin521** [comment]
As I mentioned above, `opt` doesn't consume the rest of the input stream. It either parses (and consumes) what its argument (`pint32` in your case) says, or consumes nothing and returns None.

You need something like
```
#r "nuget: FParsec"

open FParsec

let test p str =
    match run p str with
    | Success(res, _, _) -> printfn "Success: '%s' -> %A" str res
    | Failure(msg, _, _) -> printfn "Failure: %s" msg

let parse: Parser<_, unit> = ((pint32 |>> Some) <|> (noneOf ['a'] |>> (fun _ -> None))) .>>. pchar 'a'

[ "1a"; "_a" ] |> List.iter (test parse)
```

(can probably be simplified)

**Comment by tymokvo** [comment]
Got it, thank you! 

My particular case ended up being slightly easier as the parser either needed to reach the end of the stream or the stream continued with the optional field. So it is slightly more constrained than just consuming the rest of the input. 

The parser that worked for me (once I found the `eof` parser) was basically:
```fsharp
(eof >>% None) <|> (pint32 |>> Some)
```
Thanks again for the help!

**Comment by Martin521** [comment]
Then `opt pint32 .>> eof` should also work
