### ISSUE TITLE
FParsec Source Projects Won't Load in VS 2017

### ISSUE THREAD

**Issue by SirEel** [stephan-tolksdorf/fparsec#19]
I got the FParsec source from Github yesterday and tried to open the solutions in Visual Studio 2017. I had previously installed the update to VS 2017 that came out yesterday, version 15.5 Preview 4. I have both the .NET Desktop and .NET Core workflows installed.

I can open and build the "legacy" FParsec.sln in the /Build/VS11 folder. But when I try to open the "master" FParsec.sln in the root folder, VS 2017 fails to load the FParsec, FParsecCS, and Test projects. In each case the output windows says:

Could not load file or assembly 'NuGet.VisualStudio.Implementation, Version=4.4.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

The FParsec documentation says "The solution file in the root source folder does not yet properly work within the Visual Studio 2017 IDE (due to incomplete support for F# in VS). However, the folder Build/VS11 contains a solution file that works with Visual Studio 2012 and later."

Microsoft announced yesterday that with the latest updates, VS 2017 supports F# in .NET Core and .NET Standard projects. https://blogs.msdn.microsoft.com/dotnet/2017/11/15/announcing-f-support-for-net-core-and-net-standard-projects-in-visual-studio/

So I'm wondering if it's possible for me to fix this error now, or if the FParsec contributors have a timeline for resolving this.

**Comment by stephan-tolksdorf** [comment]
I haven't yet tried out the improved F# support in the latest VS 2017 update. Based on my recent experience, I doubt that the IDE support has improved enough to work with the new solution, but I'd be glad to be proven wrong.

**Comment by cloudRoutine** [comment]
@stephan-tolksdorf try this
[paketbuild.zip](https://github.com/stephan-tolksdorf/fparsec/files/1581503/paketbuild.zip)

**Comment by enricosada** [comment]
@SirEel with 61894fe493edd48baa131656786e5044dc3f38e0 the repo was migrated to .NET Sdk projects, fully supported in VS 2017.

The old VS11 projects are deleted, and not VS < 2017 is not supported anymore.

Closing.

**Comment by stephan-tolksdorf** [comment]
Just a little clarification: The new projects build well with VS 2017 and VS 2019 RC, but the F# project support in Visual Studio still has bugs that affect FParsec. Most importantly, syntax highlighting and IntelliSense of F# code may not properly reflect the active configuration or is not updated when switching the configuration. Hopefully this will be fixed soon.
