### ISSUE TITLE
Cross-platform build, maybe with Paket+FAKE?

### ISSUE THREAD

**Issue by rmunn** [stephan-tolksdorf/fparsec#21]
Since I have some free time right now, I've been trying to test out the `digit-separator` branch as requested in https://github.com/stephan-tolksdorf/fparsec/issues/2#issuecomment-284523607, but I only have a Linux development machine, so PowerShell build scripts aren't all that easy for me to use. Result: the Windows-only build process for FParsec is currently blocking me from making any progress on helping with #2.

Would you be interested in a cross-platform build process, using Paket and FAKE instead of NuGet and PowerShell? I can't guarantee that I'd have time to work on it anytime soon, but I would be willing to put in the work if you'd find it useful — and if I can find the time (always the biggest limiting factor for me). I just don't want to invest the time in making a cross-platform build process if you wouldn't find that useful.

**Comment by cloudRoutine** [comment]
You can probably use this to build on linux, just remember not to commit the project files 😜 
[paketbuild.zip](https://github.com/stephan-tolksdorf/fparsec/files/1581500/paketbuild.zip)

**Comment by stephan-tolksdorf** [comment]
@rmunn You should be able to build FParsec with Mono using the VS11 solution files. At least that used to work.

@cloudRoutine Thank you for helping out with a Paket build!

Unfortunately, I won't have time for anything FParsec related other than critical bug fixes for a few weeks. In any case, I'd rather make the existing build work on Linux than introduce another build script and dependency.
