### ISSUE TITLE
FSharp.Core Downgrade error when referencing a project using FParsec

### ISSUE THREAD

**Issue by vanceism7** [stephan-tolksdorf/fparsec#27]
Hey, thanks for making this awesome lib. I'm getting the following issue:
I created a classlib using dotnet new and installed a reference to FParsec using paket. I then made a separate console application which references this classlib. When doing this, I get an Assembly version mismatch error which causes the console app to crash on start

### Repro steps below:
1. dotnet new console -n wwh-cli -lang f#
2. dotnet new classlib -n wwh-parse -lang f#
3. dotnet new sln -n WWH
4. Copy .paket into directory
5. paket.exe init
6. Create paket.references in wwh-parse classlib with FParsec reference
7. paket.exe add FParsec --version 1.0.3
8. Ionide - Add wwh-cli project to sln 
9. Ionide - Add wwh-parse project to sln 
10. Ionide - Add wwh-parse project reference to wwh-cli console app
11. Dotnet run -- run console app and get the following errors

```
WWH\wwh-cli\wwh-cli.fsproj : warning NU1605: Detected package downgrade: FSharp.Core from 4.3.4 to 4.2.3. Reference the package directly from the project to select a different version.
WWH\wwh-cli\wwh-cli.fsproj : warning NU1605:  wwh-cli -> wwh-parse -> FSharp.Core (>= 4.3.4)
WWH\wwh-cli\wwh-cli.fsproj : warning NU1605:  wwh-cli -> FSharp.Core (>= 4.2.0)
WWH\wwh-cli\wwh-cli.fsproj : warning NU1605: Detected package downgrade: FSharp.Core from 4.3.4 to 4.2.3. Reference the package directly from the project to select a different version.
WWH\wwh-cli\wwh-cli.fsproj : warning NU1605:  wwh-cli -> wwh-parse -> FSharp.Core (>= 4.3.4)
WWH\wwh-cli\wwh-cli.fsproj : warning NU1605:  wwh-cli -> FSharp.Core (>= 4.2.0)
C:\Program Files\dotnet\sdk\2.1.4\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3277: Found conflicts between different versions of "FSharp.Core" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
[WWH\wwh-cli\wwh-cli.fsproj]

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Program.main(String[] argv)
```
### What it should do
It should run the console app

### Workarounds
If I add a reference in the console app to FParsec in paket.references file, the error goes away

Thanks for your help!

**Comment by stephan-tolksdorf** [comment]
Could you try adding 1.0.4-RC3 instead and see if that makes a difference? If not, then this is probably a package manager issue.

**Comment by vanceism7** [comment]
Oh actually I did try it with 1.0.4-RC3 and had the same issue

**Comment by vanceism7** [comment]
I just realized what you meant, I'll give it a try using standard nugget package manager/other distro methods and let you know if that fixes the issue

**Comment by vanceism7** [comment]
Ok, so I tried this out using the standard nuget package manager via the .net cli, and there were no errors, warnings, or assembly version mismatches. So this is definitely an issue with paket. I'll go ahead and mark this as closed
