### ISSUE TITLE
hex parser not parsing lower case letters

### ISSUE THREAD

**Issue by ozanas** [stephan-tolksdorf/fparsec#31]
code -
run (many hex) "AB1C12xy1z1Ax2xA3"
run (many hex) "AB12A1B"
run (many hex) "xy12x1y"
run (many hex) "ABxyAxB"
run (many hex) "xyz"

output -
Success: ['A'; 'B'; '1'; 'C'; '1'; '2']
Success: ['A'; 'B'; '1'; '2'; 'A'; '1'; 'B']
Success: []
Success: ['A'; 'B']
Success: []

Issue - the hex parser isn't working for some combinations of 'A' - 'Z' , 'a' - 'z' and '0' - '9'. It isn't working for smaller case letters as well.

**Comment by stephan-tolksdorf** [comment]
I'm not sure what you're expecting here. The hex parser is [documented](http://www.quanttec.com/fparsec/reference/charparsers.html#members.hex) to parse any char in the range '0' ‐  '9', 'a' ‐ 'f' and 'A' ‐ 'F', and nothing else.

In each of your examples the `many hex` parser stops parsing when `hex` returns an error.
