### ISSUE TITLE
FParsec Error Management and Output (AST)

### ISSUE THREAD

**Issue by vanaur** [stephan-tolksdorf/fparsec#35]
I was wondering if there was not a way to get all the errors found by FParsec (in list form?) when you need the AST returned from a function. Here is the most frequently presented way of doing things: 

```fs
let parse input =
    match run prog input with
    | Success(result, _, _) -> result
    | Failure(msg, _, _) -> failwith msg
```
With such a method, it is only possible to display one error at a time. This is not very desirable for an analysis to be performed on large files.

How could we do that? Is there a function that could be useful in this case? I looked in the documentation, and it doesn't seem to be.

Thank you.

**Comment by stephan-tolksdorf** [comment]
The error object also contains information about nested errors that triggered backtracking. 

If you want to allow multiple independent errors, you'll have to write a parser combinator that stores the current error in some list, e.g. in the user state, and then recovers from the error, e.g. by skipping to some input delimiter.
