### ISSUE TITLE
Q: Is there an ETA for 1.0.4 or 1.0.4-RC2?

### ISSUE THREAD

**Issue by bert2** [stephan-tolksdorf/fparsec#43]
I'm hitting the infinite loop issue with the `ErrorMessage.ExpectedString.String` property. I see it's fixed in master, but hasn't been released yet.

Is it currently possible to ship a new RC for 1.0.4 from master or even release it?

I'd be glad to help in any way if needed.

**Comment by stephan-tolksdorf** [comment]
I'll release a new NuGet package this week.

**Comment by stephan-tolksdorf** [comment]
I've pushed a release candidate package for version 1.1.0. Could you maybe try it out and check that it works as expected for your purposes?

**Comment by bert2** [comment]
Looks good. I upgraded my package and all unit tests are still green. Plus, I finally got rid of that ugly reflection workaround to access `ErrorMessage.ExpectedString.String` :)
