### ISSUE TITLE
FParsec's assemblies in the NuGet package are built in Debug mode.

### ISSUE THREAD

**Issue by teo-tsirpanis** [stephan-tolksdorf/fparsec#44]
It causes problems with BenchmarkDotNet, and possibly, performance degradation.

**Comment by Entomy** [comment]
Since they don't seem to keep on a patch release for this, as it's been a while, the "big data edition" was built properly, although your mileage may vary given how it's optimized differently.

**Comment by stephan-tolksdorf** [comment]
This should be fixed in the 1.1.0 release.
