### ISSUE TITLE
Promote to netstandard2.0

### ISSUE THREAD

**Issue by isaacabraham** [stephan-tolksdorf/fparsec#45]
Would it be possible to release a new version of this package that targets netstandard2.0 rather than 1.6? This has some benefits, one of which is that with the recent release of FSharp.Core 4.7, much simpler dependency graphs in Paket.

**Comment by isaacabraham** [comment]
Hi @stephan-tolksdorf just wondering if you've had any thoughts on this - happy to raise a PR to do this if it'll be accepted in principle?

**Comment by stephan-tolksdorf** [comment]
This is at the top of my todo list. I just need to find a spare hour or two.

**Comment by isaacabraham** [comment]
Fantastic :-)

**Comment by stephan-tolksdorf** [comment]
Sorry for the delay. The new NuGet package will be released this week.

**Comment by stephan-tolksdorf** [comment]
I've pushed a release candidate package for version 1.1.0. Could you maybe try it out and check that it works as expected for your purposes?

**Comment by atlemann** [comment]
The Assembly version for the net4.5 .dll does not match assembly file version. I have that issue with the current release (1.0.3) where I have a dependency like this :

![image](https://user-images.githubusercontent.com/16226914/68572748-81424280-0466-11ea-9b03-a02e3491c8ba.png)

Then
- A resolves net40 with assembly version 1.0.3.X
- B resolves netstandard1.6 with assembly version 1.0.3.Y

Which fails. The workaround is to make B multitarget net472 and netsandard2.0 so that one also resolves net40 v1.0.3.X.

It would be great if the AssemblyVersion and AssemblyFileVersion of both targets can be the same. Then I can stop multi-targeting.

net45 (here the AssemblyVersion is not correct)
![image](https://user-images.githubusercontent.com/16226914/68571985-93bb7c80-0464-11ea-8316-53790f6a5942.png)

netstandard2.0
![image](https://user-images.githubusercontent.com/16226914/68572062-c9f8fc00-0464-11ea-9862-abc5d977539e.png)

**Comment by atlemann** [comment]
And it would be great with FSharp.Core 4.7.0 in the netstandard one, if possible, since it also targets netstandard2.0.

**Comment by isaacabraham** [comment]
@stephan-tolksdorf looks good! I've just compared 1.0.3 against 1.1.0rc in terms of paket.lock files and indeed the latter is simpler - it only contains FSharp.Core as a dependency, instead of Microsoft.NETCore.Platforms and NETStandard.Library

Ironically, I think that recent advancements in paket and .NET Core versions have ameliorated the need for this to *some* extent, but this is really the best place we can now be in - thank you.

cc: @sforkmann @matthid this is important for FAKE as well.

**Comment by atlemann** [comment]
But pretty please make sure the net45 target gets the same/correct assembly version as the netstandard one, so I can remove all our multi targeting workarounds.

**Comment by stephan-tolksdorf** [comment]
The assembly version of the net45 assemblies is fixed at 1.0 because those assemblies are strongly signed. We can't remove the signing without breaking signed packages that depend on us.

I'm open to depending on a newer version of FSharp.Core if that has advantages.

**Comment by atlemann** [comment]
Uh, so every time you release a new version, the full framework assembly version will forever be 1.0.0.0, but other targets will follow the package version?

**Comment by atlemann** [comment]
Can't you just re-sign the new version?

**Comment by stephan-tolksdorf** [comment]
For signed assemblies not changing the assembly version for non-breaking updates has the advantage that the updated signed assembly can be used by signed downstream assemblies without requiring a binding redirect or rebuilding the referencing assembly.

**Comment by atlemann** [comment]
Right, then I'll have to figure out a way to force Paket to resolve the netstandard one for the net472 project I guess. Thanks for an awesome library.

**Comment by joelfbarber** [comment]
> Right, then I'll have to figure out a way to force Paket to resolve the netstandard one for the net472 project I guess. Thanks for an awesome library.

@atlemann  Did you ever figure out a workaround for this. We are also unable to get our net472 application to work because of this.

**Comment by atlemann** [comment]
@joelfbarber 

I actually got hit by this again today. The workaround was to add multiple targets for all our deps which reference FParsec (net472 and netstandard2.0) to make sure everything resolved to the net472 assemblies.

Now we'd like to remove the net472 one, but then this issue happened again. I had just forgotten about why we were doing the multi-targeting.

Maybe it would work to have an assembly targeting netstandard2.0 where you pull in all your depencencies which use FParsec. Then use that netstandard2.0 assembly in your net472 projects.

**Comment by atlemann** [comment]
@joelfbarber Actually, that didn't work either. This strong name signing is so crazy annoying. At least when done this way with one target being signed and the other not in the same package.

**Comment by atlemann** [comment]
@joelfbarber

Maybe you can try this: https://duanenewman.net/blog/post/a-better-way-to-override-references-with-packagereference/
