### ISSUE TITLE
Parsec v1.1.0 nuget package contains x64 dlls only

### ISSUE THREAD

**Issue by vslynko** [stephan-tolksdorf/fparsec#52]
It seems that [this package](https://www.nuget.org/packages/FParsec/1.1.0) contains FParsecCS.dll build with x64 platform target. Is that on purpose, or by incident?

**Comment by stephan-tolksdorf** [comment]
Do you know what's causing this in the project/msbuild files?

**Comment by vslynko** [comment]
I don't find any hints to why that happens in the repo. May be looking at build logs can give you something better.

**Comment by tpisciotta** [comment]
I just upgraded to FParsec v1.1.0 from v1.0.3 and received the following warning from Visual Studio after a compile:

There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "FParsec, Version=1.0.0.0, Culture=neutral, PublicKeyToken=40ccfc0a09edbb5d, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

**Comment by vslynko** [comment]
> There was a mismatch between the processor architecture of the ...

This is the problem manifestation I have also observed.

**Comment by stephan-tolksdorf** [comment]
Thanks a lot for reporting this issue!

Apparently the default platform when building with `dotnet build` is not `AnyCPU` 🤦 

Please try the new 1.1.1-RC NuGet packages, which should be properly cross-platform.

**Comment by tpisciotta** [comment]
I checked out the 1.1.1-RC NuGet package.  My builds no longer generate the error I communicated earlier.

Thanks for fixing that.  Can you update the 1.1.1 package from RC to be a release?
