### ISSUE TITLE
Is it possible to use FParsec in Fable?

### ISSUE THREAD

**Issue by sandeepc24** [stephan-tolksdorf/fparsec#57]

**Comment by njlr** [comment]
Do we know the reason this was closed? 

It would be great to access FParsec in Fable.

**Comment by NickDarvey** [comment]
@sandeepc24, what did you find out that led you to close this?

**Comment by njlr** [comment]
I think this will be hard to port since it uses some C# internally: https://github.com/stephan-tolksdorf/fparsec/blob/master/FParsec/FParsec.fsproj#L11

**Comment by njlr** [comment]
https://github.com/stephan-tolksdorf/fparsec/issues/65

**Comment by ShalokShalom** [comment]
[websharper](https://websharper.com/) can compile both fsharp and csharp to javascript

**Comment by smoothdeveloper** [comment]
https://github.com/cannorin/Parsec.fs
