### ISSUE TITLE
dotnetcore support?

### ISSUE THREAD

**Issue by ibnuda** [stephan-tolksdorf/fparsec#6]
Recently, I tried to use FParsec for a project in netcoreapp1.1. While it worked on netcoreapp1.0 using "portable-net45+win8+dnxcore50", the latest netcoreapp doesn't support this.

So, will you support dotnetcore?

**Comment by stephan-tolksdorf** [comment]
Yes, we're working on better .Net Core support, see #5 

However, AFAIK, you should still be able to reference the existing PCL 259 library by also referencing `Microsoft.NETCore.Portable.Compatibility`, see https://www.youtube.com/watch?v=NSjYQmu1u_k&feature=youtu.be&t=36m30s

**Comment by ibnuda** [comment]
Yeah, I used that (in project.json) just fine. But when I use dotnetcore 1.1 (the sln one), I can't do that.

![can not add](https://cloud.githubusercontent.com/assets/8169908/23718354/be4c6d22-0469-11e7-8e42-fabb76fe9efa.PNG)
(sorry, my command over mouse is not good)

**Comment by stephan-tolksdorf** [comment]
Apparently one has to manually add a [PackageTargetFallback](https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets#packagetargetfallback) to the projects file, see e.g.  https://github.com/dotnet/corefx/issues/9788#issuecomment-269924983

That the dotnet command doesn't do this automatically or at least generate a more helpful error message is beyond comprehension.

**Comment by ibnuda** [comment]
Thanks, it works. What I did was adding
```
<PackageTargetFallback Condition="'$(TargetFramework)'=='netstandard1.6'">
        $(PackageTargetFallback);portable-net45+win8+wpa81+wp8;net40-client
    </PackageTargetFallback>
```
in the PropertyGroup.
`portable-net45+win8+wpa81+wp8;` was for Chiron and `net40-client` for FParsec.
![het werkt](https://cloud.githubusercontent.com/assets/8169908/23805620/3e78f4e2-05f1-11e7-88f8-39d602df4459.PNG)

**Comment by stephan-tolksdorf** [comment]
FParsec has a `portable-net45+win8+wpa81+wp8`, i.e. PCL 259,  package too. I doubt that it's a good idea to try to use the `net40-client` library in a Core project.

**Comment by ibnuda** [comment]
I have tried that. But the result is an error.
```
Package FParsec 1.0.1 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6).
Package FParsec 1.0.1 supports: net40-client (.NETFramework,Version=v4.0,Profile=Client)
```

**Comment by stephan-tolksdorf** [comment]
Why are you using version 1.0.1 and not 1.0.2?

**Comment by ibnuda** [comment]
By default, Chiron uses 1.0.1. And by manually adding 1.0.2 as dependency, it works.
Thanks.

May I close this issue?

**Comment by stephan-tolksdorf** [comment]
Let's leave this open until the new FParsec package with netstandard support is published, so that this discussion is easier to find.

**Comment by stephan-tolksdorf** [comment]
A beta version of the FParsec NuGet package with netstandard support has been published. Please try it!
