### ISSUE TITLE
You must add a reference to assembly 'FParsecCS'

### ISSUE THREAD

**Issue by no1melman** [stephan-tolksdorf/fparsec#61]
I've just started out with FParsec, and I'm not super well versed in F#.

I found that doing

```fsharp
#r "./FParsec.dll"
#r "./FParsecCS.dll"

open FParsec

let asStr s = pstring s

let numberBetweenQuotes = 
  asStr "\"" >>. pfloat .>> asStr "\""

printfn "%A" (run numberBetweenQuotes "\"100,200.00\"") |> ignore
```

This throws an error:

> error FS0074: The type referenced through 'FParsec.CharStream`1' is defined in an assembly that is not referenced. You must add a reference to assembly 'FParsecCS'.

However, if you switch the order of the `#r` then it goes away:

```fsharp
#r "./FParsecCS.dll"
#r "./FParsec.dll"
```

Is this a known caveat - following the tutorial, it doesn't say anything about that. And it just so happens by chance that I tried it out.

Is this an fparsec thing or a f# script thing - or a combination of the both? Is it worth documenting?

**Comment by njlr** [comment]
Probably the easiest way to do this from .NET 5 onwards is using a Nuget reference:

```fsharp
#r "nuget: FParsec"
// #r "nuget: FParsec, 1.1.1" // Versioned

open FParsec

// ...
```

**Comment by no1melman** [comment]
Yeah for sure, this was definitely pre that. defo can close this in favour for that

**Comment by abelbraaksma** [comment]
Maybe a good idea to add this to the readme.md @stephan-tolksdorf?
