### ISSUE TITLE
Could we remove net45 target?

### ISSUE THREAD

**Issue by atlemann** [stephan-tolksdorf/fparsec#67]
The signed net45 pinned to assembly version 1.0.0.0 and unsigned netstandard2.0 with running versions (currently 1.1.1.0) is causing all sorts of issues. net45 is dead, could we please remove it and just have the netstandard2.0 assembly in there?

**Comment by atlemann** [comment]
See https://github.com/stephan-tolksdorf/fparsec/issues/45#issuecomment-552344681

**Comment by stephan-tolksdorf** [comment]
I've removed net45 support and will publish a new Nuget package without it. I also intend to strong name the assembly, with a properly updated assembly version.

**Comment by teo-tsirpanis** [comment]
Has been fixed.
