### ISSUE TITLE
Failure to access security critical type on Windows 8 project

### ISSUE THREAD

**Issue by mwpb** [stephan-tolksdorf/fparsec#7]
Firstly: thanks for a creating this nice library!

When running a WindowsStore (Windows 8.1) project in Xamarin Forms there is the following runtime exception when trying to access the code written with FParsec:

`"System.TypeInitializationException: The type initializer for '<StartupCode$MathsAppXF>.$parseAns' threw an exception. ---> System.TypeAccessException: Attempt by security transparent method 'FParsec.CharParsers.pchar(Char)' to access security critical type 'Microsoft.FSharp.Core.FSharpFunc`2<FParsec.CharStream`1<u>,FParsec.Reply`1<System.Char>>' failed.\r\n   at FParsec.CharParsers.pchar[u](Char c)\r\n   at <StartupCode$MathsAppXF>.$parseAns..cctor()\r\n   --- End of inner exception stack trace ---\r\n   at parseAn"  string`

We are using Xamarin Forms with Profile 111. We have also tried changing the TargetFrameworkProfile in the fsproj to Profile259 and got the same behaviour. The PCL is written in FSharp and the platform specific code in CSharp. We are using FParsec in the PCL and everything works very well for UWP and iOS projects.

Can FParsec be made to work for the WindowStore project also?

**Comment by mwpb** [comment]
I am working on making a minimal VS solution that exhibits the issue. Will comment again shortly.

**Comment by mwpb** [comment]
A minimal project exhibiting the issue can be found here: [github](https://github.com/mwpb/CrossPlatformFParsec).

It is a simplification of the code of Charles Petzold in Chapter 8 of [here](https://github.com/xamarin/xamarin-forms-book-samples) with a parser from FParsec added in.

**Comment by stephan-tolksdorf** [comment]
I was able to reproduce the problem, but I have no idea what the problem is or how to track it down.

You're probably aware of this, but just to be sure: F# is currently not supported in Windows Store UWP apps at all, see https://github.com/Microsoft/visualfsharp/issues/1096

**Comment by mwpb** [comment]
Thanks for your reply. Yes I had heard of that but what is confusing me is that in fact FParsec works very well for the UWP application in the sample! It is only the WindowsStore (Windows 8) project that is problematic. 

Thanks for taking the time to look into this problem.

**Comment by stephan-tolksdorf** [comment]
When I try to compile the UWP app with the ".NET Native" tool chain enabled (which is required for apps distributed via the store) I get the error: "GK0025 FSharp support is not yet implemented but is used by 'FSharp.Core'."

**Comment by mwpb** [comment]
Hi, yes I also get that error if I enable .NET Native. Indeed the original purpose of creating the Windows 8 project was to get around the existing problem with FSharp and UWP. 

The UWP project does indeed compile and run ok when the .NET Native toolchain is not enabled. This leads me to suspect that the issue that prevents FParsec from running on Windows 8 is not the same as the reason it doesn't run on .NET Native. Does this seem right to you?

**Comment by stephan-tolksdorf** [comment]
Yes this seems to be a different problem.
