### ISSUE TITLE
Would it be possible to update NuGet package to use FSharp.Core 4.4.0.0?

### ISSUE THREAD

**Issue by dungpa** [stephan-tolksdorf/fparsec#8]
We have an embedded plugin that builds on top of FParsec 1.0.2 from NuGet, which is built against FSharp.Core 4.3.0.0.
Due to bugfix upgrades in other F# libraries, we're forced to update to FSharp.Core 4.4.0.0, using this NuGet package https://www.nuget.org/packages/FSharp.Core/4.0.0.1

The use of FSharp.Core 4.4.0.0 causes errors at runtime since FParsec always expects FSharp.Core 4.3.0.0. If we have controls of main programs, adding FSharp.Core binding redirects to the main `app.config` would solve the mismatches. However, in the way our plugin is used, we don't have access to the main entry points. Moreover, by design, .NET applications ignore `app.config` of their libraries.

I see that there is a newer alpha at https://www.nuget.org/packages/FParsec/1.0.3-alpha-170404, but we're not in the position to use FSharp.Core 4.4.1.0 and .NET standards yet. 

I know it sounds like a minor use case, but could you please publish a NuGet package version that is compatible with FSharp.Core 4.4.0.0/VS 2015? Similar issues with explanations could be found at https://github.com/Microsoft/visualfsharp/issues/789#issuecomment-164248668.

Thank you.

**Comment by stephan-tolksdorf** [comment]
I'd like to help, but I'm not sure what the best approach would be. The official "notes and guidances" on FSharp.Core seem to no longer be updated.

Do you use the normal FParsec package, or the "Big Data Edition"? Which NuGet target framework(s) are you using?

CC @neoeinstein

**Comment by dungpa** [comment]
I use the normal FParsec package: https://www.nuget.org/packages/FParsec/1.0.2. The current target framework is `net452`.

I'm curious what updates you want to see in https://fsharp.github.io/2015/04/18/fsharp-core-notes.html . I think it's fairly safe to assume that FSharp.Core 4.4.0.0 is a good baseline these days (when F# 4.1 is just released) and libraries should depend on FSharp.Core from NuGet e.g. https://www.nuget.org/packages/FSharp.Core/4.0.0.1

**Comment by stephan-tolksdorf** [comment]
Thanks for your advice!

If published libraries should now generally depend on FSharp.Core from NuGet it would be nice if the guide spelled that out more clearly.

Would it help in your deployment scenario if the FParsec package grew a NuGet dependency on FSharp.Core >= 3.1.2.5? (According to the NuGet stats more than 15% of the FSharp.Core clients still depend on versions less than 4.)

**Comment by dungpa** [comment]
> Would it help in your deployment scenario if the FParsec package grew a NuGet dependency on FSharp.Core >= 3.1.2.5?

Yes. Indeed I have been using FsLexYacc with FSharp.Core v 4.4.0.0 https://www.nuget.org/packages/FsLexYacc.Runtime/7.0.5 thanks to its flexibility in FSharp.Core versions.

I think your proposal is a nice solution since it covers a large base right above FSharp.Core v 4.3.0.0.

**Comment by stephan-tolksdorf** [comment]
A short update: I'm working on rewriting the build system to use the new NET Core project system, building on PR #5 by @neoeinstein. Making everything work for different configurations supporting different sets of target frameworks is surprisingly difficult, but I hope to get this working in the coming days. The new NuGet FParsec packages will then reference the FSharp.Core NuGet package as discussed (barring any unforeseen blocker).

**Comment by dungpa** [comment]
Wonderful news. Thanks.

**Comment by stephan-tolksdorf** [comment]
@dungpa Could you give me an indication how time critical this is for you? Could you wait a few more days for the new NuGet package?

**Comment by dungpa** [comment]
It's not critical. We surely can wait for a few days/weeks. Please take your time :-).

**Comment by stephan-tolksdorf** [comment]
Please try the new FParsec-beta-20170521 package.

**Comment by IdeaHunter** [comment]
@stephan-tolksdorf  thanks for the new package but the problem still persists:
```
An exception of type 'System.IO.FileNotFoundException' occurred in GraphQL.Parser.dll but was not handled in user code
Additional information: Could not load file or assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```
And ILSpy tells the same:
![fparsec beta](https://user-images.githubusercontent.com/10799080/27255136-df4e55da-534c-11e7-942d-6f4f4bd45ba2.png)

**Comment by stephan-tolksdorf** [comment]
Could this possibly be due to some other F# assembly (I see FParsec.Pipes in ILSpy) not referencing the FSharp.Core NuGet package?

**Comment by stephan-tolksdorf** [comment]
Also @IdeaHunter, are you working on the same project as @dungpa, or why are you so sure it's the same problem?

**Comment by IdeaHunter** [comment]
@stephan-tolksdorf no, Im not in same project with @dungpa, but following leading me to think this is the same problem:
1) After update of FParsec from 1.2 to 1.3 exception have changed - in 1.2 it told me that FSharp.Core 4.3.0.0  could not be loaded, after i have changed it tells me that FSharp.Core 4.3.1.0 could not be loaded
2) ILSpy tell me following for my dependencies
  - Nuget Package FParsec 1.0.3-beta-20170521 targetFramework=net45
     - DLL FParsec, Version=1.0.0.0, Culture=neutral, PublicKeyToken=40ccfc0a09edbb5d
        - mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
        - FSharp.Core, Version=`4.3.1.0`, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
        - FParsecCS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=40ccfc0a09edbb5d
        - System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
     - DLL FParsecCS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=40ccfc0a09edbb5d
        - mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
        - FSharp.Core, Version=`4.3.1.0`, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
        - System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
        - System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  - Nuget Package FParsec-Pipes 0.3.1.0 targetFramework=net45
    - DLL FParsec-Pipes, Version=0.3.1.0, Culture=neutral, PublicKeyToken=a7813e45d445015c
        - mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
        - FSharp.Core, Version=`4.4.0.0`, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
        - FParsecCS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=40ccfc0a09edbb5d
        - FParsec, Version=1.0.0.0, Culture=neutral, PublicKeyToken=40ccfc0a09edbb5d
  -  Nuget Package FSharp.Core 4.0.0.1 targetFramework=net45
     - DLL FSharp.Core, Version=`4.4.0.0`, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  - Nuget Package GraphQL.Net 0.3.5 targetFramework=net45
    - DLL GraphQL.Net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=ff344d269a6f354f
        - mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
        - GraphQL.Parser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=ff344d269a6f354f
        - System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
        - FSharp.Core, Version=`4.4.0.0`, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - DLL GraphQL.Parser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=ff344d269a6f354f
        - mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
        - FSharp.Core, Version=`4.4.0.0`, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
        - FParsecCS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=40ccfc0a09edbb5d
        - FParsec, Version=1.0.0.0, Culture=neutral, PublicKeyToken=40ccfc0a09edbb5d
        - FParsec-Pipes, Version=0.3.1.0, Culture=neutral, PublicKeyToken=a7813e45d445015c
        - System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   - Nuget Package Newtonsoft.Json 10.0.2 targetFramework=net45
3) Following workaround make problem go away(i cannot use binding redirects):
```cs
ResolveEventHandler handler = null;
var assemblyToRedirect = new AssemblyName("FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
handler = (sender, args) => {
       var requestedAssembly = new AssemblyName(args.Name);
       if (requestedAssembly.Name != assemblyToRedirect.Name)
            return null;

     AppDomain.CurrentDomain.AssemblyResolve -= handler;
     return Assembly.Load(assemblyToRedirect);
 };
AppDomain.CurrentDomain.AssemblyResolve += handler;
```

**Comment by IdeaHunter** [comment]
Also not sure if Im picked the correct solution but this thing looks very suspicious
![fparsec github](https://user-images.githubusercontent.com/10799080/27255953-e6dcf624-535d-11e7-8c71-09c875c62cc7.png)

**Comment by stephan-tolksdorf** [comment]
@IdeaHunter, thank you for elaborating.

AFAIU, the references from strong-named assemblies are always to specific versions. The non-netstandard FParsec assemblies are strong-named for historical reasons, and I can't change this without breaking clients, which I'd like to avoid.

The FsLexYacc.Runtime doesn't seem to be strong-named, which is probably why referencing it worked in @dungpa's scenario.

It seems like I'll have to bump FParsec's FSharp.Core dependency to 4.0.0.1 for the non-netstandard builds if I want to better support use cases where binding redirects are not available.

**Comment by stephan-tolksdorf** [comment]
The new FParsec NuGet packages from today reference version 4.0.0.1 of the FSharp.Core package.
