### ISSUE TITLE
How to insert an indentation check into the operator precedence parser?

### ISSUE THREAD

**Issue by mrakgr** [stephan-tolksdorf/fparsec#9]
Sorry to be a bother, but could you take a look at the question I [posted on SO](http://stackoverflow.com/questions/43755987/how-to-insert-an-indentation-check-into-the-operator-precedence-parser) and tell me if extending the precedence parser with a before parse check would be viable? I'd like to place that as a feature request.

I also think that from a design perspective that instead of setting the term parser on a property, it would have been better to pass it as an argument into the expression parser. Right now I could probably hack the after string parser in the individual operators to perform the indentation check, but it would be better the check happens before the operator parser gets triggered.

**Comment by stephan-tolksdorf** [comment]
Using the  `afterStringParser` for this purpose wouldn't be a hack. The API and parser behaviour was explicitly designed to allow uses such as this. http://www.quanttec.com/fparsec/reference/operatorprecedenceparser.html#members.Operator  has some more details. The operator string parser is very cheap, so I don't think having an additional customization point for running a check before the operator would be much of an advantage.

Dynamically creating parser functions is expensive (you always incur a heap allocation and for some parsers you also have to pay for expensive setup work), which is why FParsec API's doesn't encourage it.

By the way, in case you haven't yet seen it, there's also this Wiki article discussing two ways to implement indentation-based grammars with FParsec: https://github.com/stephan-tolksdorf/fparsec/wiki/Parsing-indentation-based-syntax-with-FParsec

**Comment by mrakgr** [comment]
Well, if the `afterStirngParser` is made for this, then I guess I will use it. But consider that for every operator, I will have to create its own parser as a closure with a reference to the operator string and subtract the the length of that string from the current column in order to do the indentation check. This definitely seems like a hack since it would make more sense to do it before parsing individual operators. If there was a way to do this in `OperatorPrecedenceParser` directly before it tries applying the operator parsers, I would definitely do it instead.

    let operators expr i =
        let f (s: CharStream<_>) = if i <= s.Column then expr s else pzero s
        opp.TermParser <- f
        opp.ExpressionParser

    let rec expr s = indentations (statements expr) (tuple (operators (application (expressions expr)))) s

> `Dynamically creating parser functions is expensive`

By that did you mean did you mean the specific parser in `let f expr (s: CharStream<_>) = if i <= s.Column then expr s else pzero s` line? That one would have no choice but to become a closure due to having to hold `i`. Apart from the `expr` parser which is recursive, all the other parsers apart from the `f` one in the `operators` function could be inlined and that one in particular can't because it has to be set to the `TermParser` property. If the term parser could be passed to the OPP expression via an argument it would uncover that inlining opportunity.

I am not saying that it would necessarily happen - that depends to the specifics of the F# compiler and how aggressively it decides to do beta reduction, but the Cuda backend language I am working on definitely would. The code would look much nicer too.

Apart from that, I saw those indentation parser examples, but I do think the way I am doing is much nicer. My indentation parsers are literally one liners. Even if it turned out that F# is doing a surprisingly bad job of inlining, doing them as in the examples would not be worth the maintenance burden.

**Comment by mrakgr** [comment]
In review, the last post came out a bit more strongly that I'd like. Rather that me dumping extra work on you, if you'd be willing to allow the changes - adding a before string parser would be great for indentation checking, but would add a constant overhead everywhere else - I would be willing to look into making the modification that I want myself. If Fparsec was my own library, that is what I would definitely do. It might also be worth looking into more functional designs for the OPP parser since that might allow the unneeded extra lambda to be eliminated. It would be an interesting side project for me. What do you think?

**Comment by stephan-tolksdorf** [comment]
You seem to be overestimating the optimization capabilities of the F# compiler and the .NET JITs quite a bit. You really can't expect anything close to the heroics performed by modern whole-program optimizing C++ or Haskell compilers. If you want to get a feel for what optimizations you can expect,  compile a few F# code examples involving e.g. higher-level functions and inspect the generated code with a decompiler like `dotPeek`. And then step through the code in a debugger (without disabled optimizations) to see what machine code the JIT turns this into.

If you don't encode the indentation level into the user state, your approach will always lead to the allocations of one or more closures every time the indentation increases, which is relatively inefficient.

The full parser linked from your StackOverflow post only uses operator names with a length of 1 or 2 chars, so you'd only need two distinct `afterStringParser` instances. If the operators all have such a simple lexical form, you could alternatively just use a single instance that searches the stream backwards for the start of the operator (the overhead would be negligible if the parser directly uses the `CharStream` methods). 

If the OPP had a customizable pre-operator predicate, what should happen if the predicate changes the stream position and how should errors be handled?

Could you explain to me why you find the approaches outlined on the wiki page to be not worth the "maintenance burden"?

**Comment by mrakgr** [comment]
> You seem to be overestimating the optimization capabilities of the F# compiler and the .NET JITs quite a bit. You really can't expect anything close to the heroics performed by modern whole-program optimizing C++ or Haskell compilers. If you want to get a feel for what optimizations you can expect, compile a few F# code examples involving e.g. higher-level functions and inspect the generated code with a decompiler like dotPeek. And then step through the code in a debugger (without disabled optimizations) to see what machine code the JIT turns this into.

> If you don't encode the indentation level into the user state, your approach will always lead to the allocations of one or more closures every time the indentation increases, which is relatively inefficient.

I guess if you are confident enough to assert the above you probably know what you are talking about. But I will take your suggestion and decompile the code with `dotPeek` and see what is under the hood instead of arguing based on what should be.

> If the OPP had a customizable pre-operator predicate, what should happen if the predicate changes the stream position and how should errors be handled?

The pre-operator function would be responsible for calling the expression parser. Here is how it would look like:

```
let pre_check i expr (s: CharStream<_>)= if i <= s.Column then expr s else pzero s
let operators opp term pre_check (s: CharStream<_>) = 
    let i = s.Column
    opp.CallOpp term (pre_check i)
```

`opp.CallOpp` does not exist yet so the code gives an error at that expression, but I think the above is how it should be structured. The `CallOpp` function would be responsible for passing in the expression parser to the `pre_check` one via a higher order function.

> Could you explain to me why you find the approaches outlined on the wiki page to be not worth the "maintenance burden"?

Your approaches on the wiki do a lot of things, juggle user state, check errors, define new types specifically for the situation at hand, have complicated control flow and etecetera.

Consider the `pre_check` parser in the example above, I was not exaggerating at all when I said that that they are one liners. Let me give you some examples from my language parser.

```
let application expr (s: CharStream<_>) =
    let i = s.Column
    let expr_up (s: CharStream<_>) = if i < s.Column then expr s else pzero s
    pipe2 expr (many expr_up) ap' s
``` 

This one is for language application. If I used user state, suddenly at this point I would need to worry about conflicts because the terms being applied would need a different indentation from the rest and I'd need to back it up and restore it after the parser is done. Come to think of it, that is a bit similar to creating a closure since the call to pipe2 would not be in tail position anymore.

Also even if I was passing the indentation in `UserState` looking at the `expr_up` function the closure might as well be created without inlining since `expr_up` needs to capture `expr`.

Here is the parser for tuples:

```
let tuple expr i (s: CharStream<_>) =
    let expr_indent expr (s: CharStream<_>) = if i <= s.Column then expr s else pzero s
    sepBy1 (expr_indent (expr i)) (expr_indent comma)
    |>> function
        | _ :: _ :: _ as l -> VV l
        | x :: _ -> x
        | _ -> failwith "impossible"
    <| s
```

Again a one-liner. I am harping on this just to show how trivial parsing indentation actually is. It is not a big deal at all when written use the above technique.

I like this code and have no doubt that this is in fact how it should be written. Your argument is that my approach will create closures and not inline like I'd want, but I'd honestly argue that if F# is not inlining this stuff then it is a problem with the F# compiler and not my code and that in fact the inlining should be done. In general, programs written in CPS style such as my parser should be the ones easy to optimize into efficient imperative code for a functional compiler.

**Comment by mrakgr** [comment]
Oh, I had no idea Github would reference the link in the last commit. Please ignore it. I tend to use the commits in that repo as a diary.

One more thing, I would be willing to rewrite the indentation parser example that you made so it does not use user state if you are still not convinced that it would make things simpler. I think I could cut the size of the code to 1/3rd of what is in the example.

**Comment by mrakgr** [comment]
I've gone through the code few times with the `dnSpy` debugger and looked at it decompiled in C# with the `dotPeek` tool as you suggested. To my eyes, the code is is just a long tangle of object creation and function calls; I knew it would be bad going through the code with a debugger, but the trying to figure out what the code is doing from the disassembly would be a waste of time as there is so much noise.

Maybe I would get better readability in the disassembly, not to mention actual inlining if I converted all those `let` statements to `let inline` functions calls and replaced the lists with arrays in the `choice` combinators. Actually, merely putting those parsers in a structure would force them to instantiate as objects and there is also the fact that I am using lists which are series of objects. Unlike Haskell, I know that F# does not do any deforestation to speak off except maybe for tuples.

My conclusion is that quibbling over performance, makes very little sense in the face of how the parser is structured, and an extra closure in the operators function is hardly my biggest worry from the performance standpoint in this code based on the disassembly. It was kind of easier to argue based on an idealized model of how the code should be.

The primary lesson is that Fparsec's parsers are intended to be instantiated once at the top level so the intermediate structures get allocated only once.

But ultimately, regardless of performance I feel like I can't compromise on the kind of recursive parser structure that I am using. Any deviation from it would make the code significantly harder to read and reason about. Figuring out how to write code in this manner took me long hours of practice and this experience just gives me another reason to go ahead with my own language though for now it will be just for Cuda code.

My offer of making the precedence parser a bit nicer is still open if you feel like it. Maybe at some point, F# will get better optimizations.

**Comment by mrakgr** [comment]
The last time I posted here I thought operator parser was unsuitable for indentation, but when I tested it more thoroughly 5 days ago I realized that it is in fact wholly useless as it is right now.

```
let operators expr i =
    let f (s: CharStream<_>) = if i <= s.Column then expr s else pzero s
    opp.TermParser <- f
    opp.ExpressionParser
```

I did not realize it 2.5 weeks ago, but what happens when a new block gets opened and `expr s` gets called is that the term parser gets overwritten and  there is no way to back it up and restore it on exit. I did a bit of looking around and managed to adapt the Pratt top down parsing method for my purposes.

Here is [a talk](https://www.youtube.com/watch?v=9e_oEE72d3U) by Douglas Crockford on the method.

```
    let poperator: Parser<_,_> =
        let f c = (isAsciiIdContinue c || isAnyOf [|' ';'\t';'\n';'\"';'(';')';'{';'}';'[';']'|] c) = false
        (many1Satisfy f .>> spaces)
        >>= fun token ->
            match dict_operator.TryGetValue token with
            | true, x -> preturn x
            | false, _ -> fail "unknown operator"

    let rec led poperator term left (prec,asoc,m) =
        match asoc with
        | Associativity.Left | Associativity.None -> tdop poperator term prec |>> m left
        | Associativity.Right -> tdop poperator term (prec-1) |>> m left
        | _ -> failwith "impossible"

    and tdop poperator term rbp =
        let rec f left =
            poperator >>= fun (prec,asoc,m as v) ->
                if rbp < prec then led poperator term left v >>= loop
                else pzero
        and loop left = attempt (f left) <|>% left
        term >>= loop

    let operators expr i (s: CharStream<_>) =
        let expr_indent expr (s: CharStream<_>) = expr_indent i (<=) expr s
        let op s = expr_indent poperator s
        let term s = expr_indent expr s
        tdop op term 0 s
```

The `led` and `tdop` functions which do the actual precedence parsing are 10 lines long. Of all the parsing techniques the guy picked to hype, he definitely chose the right one. I've looked through the source for the Fparsec's precedence parser and I have absolutely no idea how I would ever improve such a beast, so I am retracting my offer to touch it up. I fully understand that the way it is written is for performance, but I have no confidence that I'd be able to write in such a style.

And rather than learn it, I am much more interested in making optimal the one that I have now.
